create table public.p02_logs_execucao (
  id bigint generated by default as identity not null,
  sessao_id bigint not null,
  evolucao_index integer not null,
  -- tokens_antes / tokens_depois: zerados a partir da migration_logs_indicadores.sql
  -- (eram estimativas tiktoken/GPT-4o; substituídos pelas métricas reais Ollama abaixo)
  tokens_antes integer not null default 0,
  tokens_depois integer not null default 0,
  porcentagem_reducao real not null default 0,
  tempo_execucao_segundos real not null,
  qtde_piis_novos integer null default 0,
  houve_duvida boolean null default false,
  created_at timestamp with time zone null default now(),
  fase_atual character varying(30) null default 'linha_a_linha'::character varying,
  tamanho_ngram integer null,
  texto_original text null,
  texto_pre_llm text null,
  llm_raw_response text null,
  houve_falha boolean not null default false,
  status_erro character varying(30) null,           -- "erro_stop_reason" | "timeout" | "erro" | null
  -- Métricas reais da API Ollama (adicionadas em migration_logs_indicadores.sql)
  prompt_eval_count integer null,           -- tokens reais do prompt
  eval_count integer null,                  -- tokens reais gerados
  eval_tokens_per_second real null,         -- throughput (tokens/s)
  total_duration_ollama_sec real null,      -- tempo total medido pelo Ollama
  load_duration_sec real null,              -- tempo de carregamento do modelo
  prompt_eval_duration_sec real null,       -- tempo de prefill
  eval_duration_sec real null,              -- tempo de decoding
  done_reason character varying(30) null,   -- "stop" | "length" | outro
  qtde_tentativas smallint null default 1,  -- retentativas na fase linha_a_linha
  chars_reducao_boilerplate integer null,   -- chars economizados por boilerplates
  raciocinio text null,                     -- CoT thinking do modelo (thinking tokens)
  resposta_bruta text null,                 -- texto bruto retornado pelo LLM antes do parse JSON
  constraint p02_logs_execucao_pkey primary key (id),
  constraint p02_logs_execucao_sessao_id_fkey foreign KEY (sessao_id) references p02_sessoes (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_p02_logs_resume on public.p02_logs_execucao using btree (sessao_id, evolucao_index desc) TABLESPACE pg_default;

create index IF not exists idx_p02_logs_fase on public.p02_logs_execucao using btree (sessao_id, fase_atual) TABLESPACE pg_default;