create table public.p02_conhecimento (
  id bigint generated by default as identity not null,
  sessao_id bigint not null,
  tipo character varying(20) not null,
  texto_original text not null,
  id_local_sessao integer not null,
  created_at timestamp with time zone null default now(),
  constraint p02_conhecimento_pkey primary key (id),
  constraint p02_conhecimento_sessao_texto_unique unique (sessao_id, tipo, texto_original),
  constraint p02_conhecimento_sessao_id_fkey foreign KEY (sessao_id) references p02_sessoes (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_p02_conhecimento_sessao on public.p02_conhecimento using btree (sessao_id) TABLESPACE pg_default;

create index IF not exists idx_p02_conhecimento_tipo on public.p02_conhecimento using btree (tipo) TABLESPACE pg_default;