create table public.p02_sessoes (
  id bigint generated by default as identity not null,
  nome_identificador character varying(100) not null,
  modelo_llm character varying(50) not null,
  temperatura real not null,
  hardware_info text null,
  config_ngram_min integer null,
  config_ngram_max integer null,
  status text null default 'iniciado'::character varying,
  data_inicio timestamp with time zone null default now(),
  ultima_atualizacao timestamp with time zone null default now(),
  hash text null,
  tag_ini character varying(4) null,
  tag_fim character varying(4) null,
  constraint p02_sessoes_teste_pkey primary key (id),
  constraint p02_sessoes_teste_nome_identificador_key unique (nome_identificador)
) TABLESPACE pg_default;