create table public.p02_brkga_simular_injection (
  id bigint generated always as identity not null,
  log_llm_id bigint not null,
  raciocinio text null,
  resposta_bruta text null,
  llm_raw_response text null,
  status_erro character varying(30) null,
  done_reason character varying(255) null,
  total_duration_sec double precision null,
  load_duration_sec double precision null,
  prompt_eval_count integer null,
  prompt_eval_duration_sec double precision null,
  eval_count integer null,
  eval_duration_sec double precision null,
  eval_tokens_per_second double precision null,
  recall double precision null,
  precision double precision null,
  f1 double precision null,
  f2 double precision null,
  houve_falha boolean not null default false,
  prompt_enviado text null,
  created_at timestamp without time zone not null default now(),
  loop_detectado boolean null,
  loop_tipo character varying(50) null,
  posicao_corte integer null,
  tamanho_raciocinio_original integer null,
  tamanho_raciocinio_truncado integer null,
  ratio_raciocinio_aproveitado double precision null,
  constraint p02_brkga_simular_injection_pkey primary key (id),
  constraint p02_brkga_simular_injection_log_fkey foreign KEY (log_llm_id) references p02_brkga_logs_llm (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_brkga_simular_injection_log on public.p02_brkga_simular_injection using btree (log_llm_id) TABLESPACE pg_default;